/**
 * Renders src/tokens/index.ts into src/styles/tokens.css.
 * The generated file is gitignored; predev/prebuild/pretest hooks keep it fresh.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { motion, palette, shape } from '../src/tokens/index.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, '../src/styles/tokens.css');

function block(name: string, vars: Record<string, string>): string {
  const lines = Object.entries(vars)
    .map(([key, value]) => `  ${key}: ${value};`)
    .join('\n');
  return `  /* ${name} */\n${lines}`;
}

const css = `/* GENERATED by scripts/build-tokens.ts — do not edit. */
:root {
  color-scheme: dark;
${block('palette', palette)}

${block('motion', motion)}

${block('shape & type', shape)}
}
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, css);
console.log(`tokens.css written (${Object.keys({ ...palette, ...motion, ...shape }).length} tokens)`);
