"""initial schema

Revision ID: 1c879ff213ef
Revises: 
Create Date: 2026-07-31 18:08:24.803990

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '1c879ff213ef'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('layout_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_ts', ['ts'], unique=False)

    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('arch', sa.String(), nullable=True),
    sa.Column('agent_version', sa.String(), nullable=True),
    sa.Column('boot_ts', sa.Integer(), nullable=True),
    sa.Column('labels_json', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('config_json', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('ports_json', sa.String(), nullable=True),
    sa.Column('labels_json', sa.String(), nullable=True),
    sa.Column('bifrost_meta_json', sa.String(), nullable=True),
    sa.Column('started_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'container_id')
    )
    op.create_table('disks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('capacity_bytes', sa.Integer(), nullable=True),
    sa.Column('smart_status', sa.String(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('power_on_hours', sa.Integer(), nullable=True),
    sa.Column('realloc_sectors', sa.Integer(), nullable=True),
    sa.Column('pending_sectors', sa.Integer(), nullable=True),
    sa.Column('wear_pct', sa.Float(), nullable=True),
    sa.Column('smart_json', sa.String(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'serial')
    )
    op.create_table('endpoint_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('check_kind', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('interval_s', sa.Integer(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('expect_status', sa.Integer(), nullable=True),
    sa.Column('last_ok', sa.Boolean(), nullable=True),
    sa.Column('last_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_checked', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fs_mounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('mountpoint', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('fstype', sa.String(), nullable=True),
    sa.Column('total_bytes', sa.Integer(), nullable=True),
    sa.Column('used_bytes', sa.Integer(), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'mountpoint')
    )
    op.create_table('k8s_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('discovered_node_id', sa.Integer(), nullable=True),
    sa.Column('auth_mode', sa.String(), nullable=False),
    sa.Column('kubeconfig_path', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('ca_pem', sa.String(), nullable=True),
    sa.Column('insecure_skip_verify', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_sync', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discovered_node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('k8s_cronjobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('last_run_ts', sa.Integer(), nullable=True),
    sa.Column('last_result', sa.String(), nullable=True),
    sa.Column('last_duration_s', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name')
    )
    op.create_table('k8s_ingresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hosts_json', sa.String(), nullable=True),
    sa.Column('tls', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name')
    )
    op.create_table('k8s_pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('ready', sa.Boolean(), nullable=True),
    sa.Column('restarts', sa.Integer(), nullable=True),
    sa.Column('node_name', sa.String(), nullable=True),
    sa.Column('owner_kind', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name')
    )
    op.create_table('k8s_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('cluster_ip', sa.String(), nullable=True),
    sa.Column('ports_json', sa.String(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name')
    )
    op.create_table('k8s_workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('replicas_desired', sa.Integer(), nullable=True),
    sa.Column('replicas_ready', sa.Integer(), nullable=True),
    sa.Column('images_json', sa.String(), nullable=True),
    sa.Column('labels_json', sa.String(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'kind', 'namespace', 'name')
    )
    op.create_table('k8s_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cronjob_id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=False),
    sa.Column('started_ts', sa.Integer(), nullable=True),
    sa.Column('finished_ts', sa.Integer(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cronjob_id'], ['k8s_cronjobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cronjob_id', 'job_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('k8s_job_runs')
    op.drop_table('k8s_workloads')
    op.drop_table('k8s_services')
    op.drop_table('k8s_pods')
    op.drop_table('k8s_ingresses')
    op.drop_table('k8s_cronjobs')
    op.drop_table('k8s_clusters')
    op.drop_table('fs_mounts')
    op.drop_table('endpoint_checks')
    op.drop_table('disks')
    op.drop_table('containers')
    op.drop_table('widgets')
    op.drop_table('settings')
    op.drop_table('nodes')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_ts')

    op.drop_table('events')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
