"""alert rules

Revision ID: 6e3d1c5a7c1b
Revises: f2eafc3785f2
Create Date: 2026-07-31 19:38:13.442466

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '6e3d1c5a7c1b'
down_revision: str | None = 'f2eafc3785f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('min_severity', sa.String(), nullable=False),
    sa.Column('notifier', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('cooldown_s', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
