"""k8s kubeconfig content

Revision ID: f2eafc3785f2
Revises: 1c879ff213ef
Create Date: 2026-07-31 19:19:37.790116

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'f2eafc3785f2'
down_revision: str | None = '1c879ff213ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kubeconfig_content', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('k8s_clusters', schema=None) as batch_op:
        batch_op.drop_column('kubeconfig_content')

    # ### end Alembic commands ###
