#!/usr/bin/env bash
# Render Caddy vhosts for the Docker services bifrost advertises
# (GET /api/v1/gateway/routes) and hot-reload Caddy when they change.
#
# Container edition: runs next to caddy in the same compose. Rendering writes
# to the shared bifrost.d volume; reloading POSTs the Caddyfile to caddy's
# admin API (Content-Type: text/caddyfile — caddy adapts it itself, so this
# image needs no caddy binary or DNS plugins). Node names resolve through
# Docker's DNS, which on a tailnet host resolves peers to their 100.x IPs;
# NODE_ADDR_<NAME> env vars override per node.
#
# Hand-written blocks always win: hosts already declared in the static
# Caddyfile are skipped here. Exits quietly when the hub is unreachable (or
# predates the endpoint) and rolls back if caddy rejects the new config.
set -euo pipefail

HUB_URL=${HUB_URL:-http://bifrost-hub:8000}
DOMAIN=${DOMAIN:?set DOMAIN to the gateway zone, e.g. example.net}
STATIC_CADDYFILE=${STATIC_CADDYFILE:-/etc/caddy/Caddyfile}
OUT=${OUT:-/etc/caddy/bifrost.d/routes.caddy}
CADDY_ADMIN=${CADDY_ADMIN:-http://caddy:2019}
INTERVAL=${INTERVAL:-120}

sync_once() {
	local routes new current
	routes=$(curl -fsS --max-time 10 "$HUB_URL/api/v1/gateway/routes?domain=$DOMAIN") || {
		echo "hub unreachable; leaving $OUT untouched" >&2
		return 0
	}
	# A hub without the endpoint serves the SPA (HTML, status 200) for unknown paths.
	printf '%s' "$routes" | python3 -c 'import json,sys; json.load(sys.stdin)' 2>/dev/null || {
		echo "hub response is not JSON (endpoint not deployed yet?); leaving $OUT untouched" >&2
		return 0
	}

	new=$(
		ROUTES="$routes" python3 - "$STATIC_CADDYFILE" <<'PY'
import json, os, re, socket, sys

routes = json.loads(os.environ["ROUTES"])
static = open(sys.argv[1]).read()

# Site addresses declared by hand: column-0 lines that open a block.
static_hosts = set()
for line in static.splitlines():
    m = re.match(r"^([A-Za-z0-9*][A-Za-z0-9.*-]*(?:\s*,\s*[A-Za-z0-9*][A-Za-z0-9.*-]*)*)\s*\{", line)
    if m:
        static_hosts.update(h.strip() for h in m.group(1).split(","))

def node_addr(node: str) -> str | None:
    override = os.environ.get("NODE_ADDR_" + node.upper().replace("-", "_"))
    if override:
        return override
    try:
        addr = socket.gethostbyname(node)
    except OSError:
        return None
    return None if addr.startswith("127.") else addr

lines = [
    "# GENERATED by bifrost-caddy-sync — do not edit, changes are overwritten.",
    "# Host-matched handle blocks, imported INSIDE the wildcard site: every",
    "# route rides the one wildcard certificate and wins over the fallthrough.",
]
for r in routes:
    if r["host"] in static_hosts:
        continue
    addr = node_addr(r["node"])
    if addr is None:
        print(f"skipping {r['host']}: cannot resolve node {r['node']}", file=sys.stderr)
        continue
    m = "bf_" + re.sub(r"[^A-Za-z0-9_]", "_", r["host"])
    # bifrost.path redirects the bare root, mirroring a hand-written redir.
    redirect = f"\n\tredir / {r['path']} 302" if r.get("path") else ""
    lines.append(
        f"\n@{m} host {r['host']}\nhandle @{m} {{{redirect}\n\treverse_proxy {addr}:{r['port']}\n}}"
    )
print("\n".join(lines))
PY
	)

	current=$(cat "$OUT" 2>/dev/null || true)
	if [ "$new" = "$current" ]; then
		return 0
	fi

	printf '%s\n' "$new" >"$OUT"
	if curl -fsS -X POST "$CADDY_ADMIN/load" -H "Content-Type: text/caddyfile" \
		--data-binary @"$STATIC_CADDYFILE" >/dev/null; then
		echo "updated $OUT and reloaded caddy"
	else
		printf '%s\n' "$current" >"$OUT"
		echo "caddy rejected the new config; restored previous $OUT" >&2
		return 1
	fi
}

if [ "${1-}" = "--loop" ]; then
	[ -f "$OUT" ] || printf '# GENERATED by bifrost-caddy-sync — routes will appear here.\n' >"$OUT"
	while :; do
		sync_once || true
		sleep "$INTERVAL"
	done
else
	sync_once
fi
